name: Matrix Testing

run-name: ${{ github.actor }} is running Matrix_Testing pipeline on GitHub Actions

on:
  push:
    branches: 
      - release/*
  pull_request:
    branches: 
      - release/*

  workflow_dispatch:

jobs:

  matrix_testing:

    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ['16', '17', '>=18']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        lfs: ${{ matrix.test-group == 'content' }}
        persist-credentials: 'false'

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build:prod --if-present
        npm run test:headless
