# Opcional - O name do fluxo de trabalho como aparecerá na guia "Ações" do repositório GitHub
name: CI

# Controla quando o fluxo de trabalho será executado
on:
  # Aciona o fluxo de trabalho em eventos push ou pull request, mas apenas para a branch "main"
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Permite que você execute este fluxo de trabalho manualmente na guia Actions.
  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta por um ou mais trabalhos que podem ser executados sequencialmente ou em paralelo.
jobs:

  checkout:
  
    runs-on: ubuntu-latest

    steps:

       # Verifica seu repositório no runner
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Define a versao do node como 14x
      - name: Define Node.js Version
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      # Instala as dependencias do projeto
      - name: Install dependencies
        run: cd my-app && npm install

  build_application:

    runs-on: ubuntu-latest
    needs: checkout
  
    steps:
      
      # Faz o Build da Aplicacao
      - name: Build Application
        run: cd my-app && npm run build --if-present

      # Faz o teste da Aplicacao
      - name: Test Application
        run: echo "TEST!"

      # Faz upload do artefato gerado durante o build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: my-app/dist
